export * from './apiController.service';
import { ApiControllerService } from './apiController.service';
export * from './basicErrorController.service';
import { BasicErrorControllerService } from './basicErrorController.service';
export * from './explorerController.service';
import { ExplorerControllerService } from './explorerController.service';
export * from './serviceWalletController.service';
import { ServiceWalletControllerService } from './serviceWalletController.service';
export * from './walletController.service';
import { WalletControllerService } from './walletController.service';
export const APIS = [ApiControllerService, BasicErrorControllerService, ExplorerControllerService, ServiceWalletControllerService, WalletControllerService];
