/**
 * KMP API
 * KMP 에서 제공하는 API를 확인하고 테스트 해볼 수 있습니다.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jdlee726@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ExportHistory {
    amount_btc?: number;
    date?: string;
    exchange_rate_then?: string;
    time?: string;
    tx?: string;
    type?: string;
    value_now?: string;
    value_then?: string;
}
