/**
 * KMP API
 * KMP 에서 제공하는 API를 확인하고 테스트 해볼 수 있습니다.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jdlee726@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Transaction } from './transaction';


export interface RawBlock {
    bits?: number;
    block_index?: number;
    fee?: number;
    hash?: string;
    height?: number;
    main_chain?: boolean;
    mrkl_root?: string;
    n_tx?: number;
    nonce?: number;
    prev_block?: string;
    received_time?: number;
    relayed_by?: string;
    size?: number;
    time?: number;
    tx?: Array<Transaction>;
    ver?: number;
}
