/**
 * KMP API
 * KMP 에서 제공하는 API를 확인하고 테스트 해볼 수 있습니다.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jdlee726@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TickerItem } from './tickerItem';


export interface Ticker {
    AUD?: TickerItem;
    BRL?: TickerItem;
    CAD?: TickerItem;
    CHF?: TickerItem;
    CLP?: TickerItem;
    CNY?: TickerItem;
    DKK?: TickerItem;
    EUR?: TickerItem;
    GBP?: TickerItem;
    HKD?: TickerItem;
    ISK?: TickerItem;
    JPY?: TickerItem;
    KRW?: TickerItem;
    NZD?: TickerItem;
    PLN?: TickerItem;
    RUB?: TickerItem;
    SEK?: TickerItem;
    SGD?: TickerItem;
    THB?: TickerItem;
    TWD?: TickerItem;
    USD?: TickerItem;
}
