/**
 * KMP API
 * KMP 에서 제공하는 API를 확인하고 테스트 해볼 수 있습니다.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jdlee726@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Input } from './input';
import { Output } from './output';


export interface Transaction {
    block_height?: number;
    double_spend?: boolean;
    fee?: number;
    hash?: string;
    inputs?: Array<Input>;
    lock_time?: number;
    out?: Array<Output>;
    relayed_by?: string;
    result?: number;
    size?: number;
    time?: number;
    tx_index?: number;
    ver?: number;
    vin_sz?: number;
    vout_sz?: number;
}
